source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'booqcms', path: '../booqcms'
gem 'bourbon'
gem 'neat'
gem 'turbolinks'
gem 'inline_svg'
gem 'best_in_place', github: 'bernat/best_in_place'
gem 'simple_form'
gem 'responders'



group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
end
